name: 'dotnet-unit-test'
description: 'Run unit tests for a .NET project'

inputs:
  build-version:
    description: 'Build version'
    required: false
    default: '0.0.0.0'

  project-name:
    description: 'Name of the project'
    required: true

  project-type:
    description: 'Type of the project file (e.g., csproj or sln)'
    required: true

  filter:
    description: 'The filter to apply to the test run (e.g., TestCategory=Unit)'
    required: false
    default: ''
  
  test-settings:
    description: 'The path to the test settings file'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Set Working Directory
      id: set-working-directory
      shell: pwsh
      run: |
        $projectFileName  = "${{ inputs.project-name }}.${{ inputs.project-type }}"
        $projectFile      = (Get-ChildItem -Path . -Filter $projectFileName -Recurse).FullName
        $workingDirectory = [System.IO.Path]::GetDirectoryName($projectFile)
        Write-Host "Working Directory: $workingDirectory"

        $OutputString = "working-directory=$workingDirectory"
        $OutputString | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

    - name: Unit Tests and Code Coverage
      env:
        artifactStagingDirectory: ${{ github.workspace }}/artifact_staging
      shell: pwsh
      working-directory: ${{ steps.set-working-directory.outputs.working-directory }}
      run: |
        $projectFileName      = "${{ inputs.project-name }}.${{ inputs.project-type }}"
        $projectFile          = (Get-ChildItem -Path . -Filter $projectFileName -Recurse).FullName
        $runSettingsFileName  = "${{ inputs.test-settings }}"
        $runSettingsFile      = (Get-ChildItem -Path . -Filter $runSettingsFileName -Recurse).FullName
        $testDirectory        = [System.IO.Path]::GetDirectoryName($projectFile)
        $testFilterExpression = "${{ inputs.filter }}"
        $testReportFile       = "${{ env.artifactStagingDirectory }}/TestOutput.${{ inputs.project-name }}.${{ inputs.build-version }}.xml"

        Write-Host "Project File Name             : $projectFileName"
        Write-Host "Project File                  : $projectFile"
        Write-Host "Run Settings File Name        : $runSettingsFileName"
        Write-Host "Run Settings File             : $runSettingsFile"
        Write-Host "Test Directory                : $testDirectory"
        Write-Host "Initial Test Filter Expression: $testFilterExpression"
        Write-Host "Test Report File              : $testReportFile"
        
        Set-Location $testDirectory
        Write-Host "Changed directory to          : $testDirectory"
        
        Write-Host "Executing dotnet test command with the following parameters:"
        Write-Host "Test Filter Expression        : $testFilterExpression"
        Write-Host "Run Settings File Argument    : $runSettingsFile"
        Write-Host "Test Report File              : $testReportFile"
        
        $filterToken         = $testFilterExpression
        $settingsToken       = $runSettingsFile
        $loggerToken         = ('"trx;LogFileName=' + $testReportFile + '"')
        $collectToken        = '"Xplat Code Coverage"'
        $argumentsCollection = @(
            "test"
        )
        
        if(![string]::IsNullOrEmpty($testFilterExpression)) {
            $argumentsCollection += ('--filter "' + $testFilterExpression + '"')
        }
        
        if(![string]::IsNullOrEmpty($runSettingsFile)) {
            $argumentsCollection += ('--settings "' + $runSettingsFile + '"')
        }
        
        $argumentsCollection += "--no-build"
        $argumentsCollection += "-l:" + ('"trx;LogFileName=' + $testReportFile + '"')
        $argumentsCollection += "--collect:" + '"Xplat Code Coverage"'
        
        $arguments = $argumentsCollection -join " "
        
        Start-Process -FilePath "dotnet" -ArgumentList $arguments -NoNewWindow -Wait
  
    - name: Publish Test Results
      env:
        artifactStagingDirectory: ${{ github.workspace }}/artifact_staging
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        check_name: Unit Tests Results
        files: |
          ${{ env.artifactStagingDirectory }}/TestOutput.${{ inputs.project-name }}.${{ inputs.build-version }}.xml

    - name: Upload Unit Tests Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ${{ env.artifactStagingDirectory }}/TestOutput.${{ inputs.project-name }}.${{ inputs.build-version }}.xml

    - name: Copy Coverage File to Artifact Staging Directory
      env:
        artifactStagingDirectory: ${{ github.workspace }}/artifact_staging
      shell: pwsh
      run: |
        # Get the most recently modified 'coverage.cobertura.xml' file from the './TestResults' directory and its subdirectories
        $coverageFile = Get-ChildItem `
            -Path '.' `
            -Recurse -Filter 'coverage.cobertura.xml' `
            -File | Sort-Object -Property LastWriteTime -Descending | Select-Object -First 1 -ExpandProperty FullName

        # Define the new file name and destination path
        $newFileName = 'coverage.cobertura.${{ inputs.project-name }}.${{ inputs.build-version }}.xml'
        $destinationPath = Join-Path -Path ${{ env.artifactStagingDirectory }} -ChildPath $newFileName

        # Ensure the destination directory exists
        if (-not (Test-Path -Path ${{ env.artifactStagingDirectory }})) {
            New-Item -ItemType Directory -Path ${{ env.artifactStagingDirectory }}
        }

        # Copy the most recently modified 'coverage.cobertura.xml' file to the artifact staging directory with the new file name
        Copy-Item -Path $coverageFile -Destination $destinationPath

    - name: Upload Code Coverage Results
      env:
        artifactStagingDirectory: ${{ github.workspace }}/artifact_staging
      uses: actions/upload-artifact@v4
      with:
        name: test-coverage
        path: ${{ env.artifactStagingDirectory }}/coverage.cobertura.${{ inputs.project-name }}.${{ inputs.build-version }}.xml

    - name: New Code Coverage Summary
      id: new-coverage-file
      shell: pwsh
      run: |
        $xmlSource        = "${{ env.artifactStagingDirectory }}/coverage.cobertura.${{ inputs.project-name }}.${{ inputs.build-version }}.xml"
        $outputFile       = "${{ env.artifactStagingDirectory }}/coverage.cobertura.${{ inputs.project-name }}.${{ inputs.build-version }}.md"
        $showBadges       = $true
        $showPackages     = $true
        $showClassSummary = $false
        $showClassDetails = $false

        # Determine if the source is a URL or a file path
        if ($xmlSource -match "^http(s)?://") {
            # Load XML from URL
            $xml = [xml](Invoke-WebRequest -Uri $xmlSource).Content
        } else {
            # Load XML from file
            [xml]$xml = Get-Content -Path $xmlSource
        }

        # Extract coverage rates
        $lineCoverage = [math]::Round($xml.coverage.'line-rate', 2) * 100
        $branchCoverage = [math]::Round($xml.coverage.'branch-rate', 2) * 100

        # Start building the markdown content
        $markdown = @"
        # Unit Tests Code Coverage Report
        "@

        if ($showBadges) {
            $markdown += @"


        ![Line Coverage](https://img.shields.io/badge/Line%20Coverage-$lineCoverage%25-success?style=flat) ![Branch Coverage](https://img.shields.io/badge/Branch%20Coverage-$branchCoverage%25-success?style=flat)

        "@
        }

        $markdown += @"

        ## Overview

        - **Lines Covered**: $($xml.coverage.'lines-covered')
        - **Valid Lines**: $($xml.coverage.'lines-valid')
        - **Branches Covered**: $($xml.coverage.'branches-covered')
        - **Valid Branches**: $($xml.coverage.'branches-valid')

        "@

        if ($showPackages) {
            $markdown += @"

        ## Packages

        "@

            foreach ($package in $xml.coverage.packages.package) {
                $packageName = $package.name
                $packageLineRate = [math]::Round($package.'line-rate', 2) * 100
                $packageBranchRate = [math]::Round($package.'branch-rate', 2) * 100
                $packageComplexity = $package.complexity

                $markdown += @"

        ### Package: $packageName

        - **Line Coverage Rate**: $packageLineRate%
        - **Branch Coverage Rate**: $packageBranchRate%
        - **Complexity**: $packageComplexity

        "@

                if ($showClassSummary) {
                    $markdown += @"

        #### Classes Summary

        | Class Name                            | Filename            | Line Coverage Rate | Branch Coverage Rate | Complexity |
        |---------------------------------------|---------------------|--------------------|----------------------|------------|

        "@

                    foreach ($class in $package.classes.class) {
                        $className = $class.name
                        $classFilename = $class.filename
                        $classLineRate = [math]::Round($class.'line-rate', 2) * 100
                        $classBranchRate = [math]::Round($class.'branch-rate', 2) * 100
                        $classComplexity = $class.complexity

                        $markdown += @"
        | $className | $classFilename | $classLineRate% | $classBranchRate% | $classComplexity |

        "@
                    }
                }

                if ($showClassDetails) {
                    $markdown += "`n#### Class Details`n"

                    foreach ($class in $package.classes.class) {
                        $className = $class.name
                        $classFilename = $class.filename
                        $classLineRate = [math]::Round($class.'line-rate', 2) * 100
                        $classBranchRate = [math]::Round($class.'branch-rate', 2) * 100
                        $classComplexity = $class.complexity

                        $markdown += @"

        ##### $className

        - **Filename**: `$classFilename`
        - **Line Coverage Rate**: $classLineRate%
        - **Branch Coverage Rate**: $classBranchRate%
        - **Complexity**: $classComplexity

        ###### Lines

        | Line Number | Hits | Branch |
        |-------------|------|--------|

        "@

                        foreach ($line in $class.lines.line) {
                            $lineNumber = $line.number
                            $hits = $line.hits
                            $branch = $line.branch

                            $markdown += @"
        | $lineNumber | $hits | $branch |

        "@
                        }
                    }
                }
            }
        }

        # Write the markdown content to the output file
        $markdown | Out-File -FilePath $outputFile -Encoding utf8

    - name: Upload Code Coverage Summary
      uses: actions/upload-artifact@v4
      with:
        name: unit-tests-coverage-summary
        path: ${{ env.artifactStagingDirectory }}/coverage.cobertura.${{ inputs.project-name }}.${{ inputs.build-version }}.md

    - name: Collect Job Summary
      working-directory: ${{ env.artifactStagingDirectory }}  
      shell: pwsh
      run: |
        # Read the content of the coverage report file
        $content = Get-Content -Path "${{ env.artifactStagingDirectory }}/coverage.cobertura.${{ inputs.project-name }}.${{ inputs.build-version }}.md"

        # Append the content to the GitHub Actions job summary to display it in the workflow run details
        $content | Add-Content -Path $env:GITHUB_STEP_SUMMARY -Encoding utf8
